imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@ABUserBundle/Resources/config/services.yml" }
    - { resource: "@ABBundle/Resources/config/services.yml" }

parameters:
    fos_user.template.engine: twig

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ABBundle, ABUserBundle, FOSUserBundle ]
    #java: /usr/bin/java
    filters:
        less:
            node: %node_binary%
            node_paths: [ %nodejsmodules% ]
            apply_to: "\.less$"
        cssrewrite: ~
        uglifyjs2:
            bin: %uglify_binary%
            apply_to: "\.js$"
    # assets:
    #     bootstrap_css:
    #         inputs:
    #             - %kernel.root_dir%/../src/AB/Bundle/Resources/public/bootstrap/less/bootstrap.less
    #         filters:
    #             - less
    #             - cssrewrite
    #         output: css/bootstrap.css

#FOSUserBundle configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AB\Bundle\Entity\User
    service:
        user_manager: pugx_user_manager
    from_email:
        address: academic.buddy@gmail.com
        sender_name: Academic Buddy
#    registration:
#        confirmation:
#            form_email:
#            enabled: true
#PUGXMultiUserBundle configuration
pugx_multi_user:
  users:
    mentor:
        entity:
          class: AB\Bundle\Entity\Mentor
        registration:
          form:
            type: AB\Bundle\Form\Type\MentorRegistrationType
            name: fos_user_registration_form
            validation_groups:  [Registration, Default]
          template: ABBundle:Registration:register.mentor.html.twig
        profile:
          form:
            type: AB\Bundle\Form\Type\MentorProfileType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default]
    pupil:
        entity:
          class: AB\Bundle\Entity\Pupil
        registration:
          form:
            type: AB\Bundle\Form\Type\PupilRegistrationType
          template: ABBundle:Registration:register.pupil.html.twig
        profile:
          form:
            type: AB\Bundle\Form\Type\PupilProfileType
#Bootstrap configuration
braincrafted_bootstrap:
    output_dir: 
    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.11.1.js
    css_preprocessor: less # "less", "lessphp" or "none"
    fonts_dir: %kernel.root_dir%/../web/fonts
    auto_configure:
        assetic: true
        twig: true
        knp_menu: true
        knp_paginator: true
    customize:
        variables_file: %kernel.root_dir%/../src/AB/Bundle/Resources/public/bootstrap/less/variables.less
        #bootstrap_output: %kernel.root_dir%/../src/AB/Bundle/Resources/public/bootstrap/less/bootstrap.less
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig
#Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
    username:   %mailer_user%
    password:   %mailer_password%
    spool:     { type: memory }

knp_menu:
    twig:
        template: ABBundle:Default:knp_menu.html.twig