main:
    resource: "@ABBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"


#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

fos_user_profile_show:
    pattern: /profile
    defaults: { _controller: ABBundle:Default:index }
#fos_user_profile_edit:
#    pattern: /profile/edit
#    defaults: { _controller: RefreshingAppBundle:Profile:edit }

settings:
       pattern: /settings
       defaults: { _controller: ABBundle:Profile:settings }

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
login_check:
    path:   /login_check
logout:
    path:   /logout
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
