#ab_routes:
#    resource: "@ABBundle/Controller"
#    type:     annotation
mentor_registration:
    path:  /register/mentor
    defaults: { _controller: ABBundle:Registration:registerMentor }

pupil_registration:
    path:  /register/pupil
    defaults: { _controller: ABBundle:Registration:registerPupil }

# Enables URLs without locale, i.e. just domain.lt/about/oxbridge.
# JMSI18nRoutingBundle could lead to a more elegant solution, 
# but since we only need 4 routes to be translated, it's fine to duplicate routes.

home_noloc:
    path: /
    defaults: {_controller: FrameworkBundle:Redirect:redirect, route: home }

about_oxbridge_noloc:
    path: /about/oxbridge
    defaults: {_controller: FrameworkBundle:Redirect:redirect, route: about_oxbridge }

about_uk_noloc:
    path: /about/uk
    defaults: {_controller: FrameworkBundle:Redirect:redirect, route: about_uk }

support_noloc:
    path: /support
    defaults: {_controller: FrameworkBundle:Redirect:redirect, route: support }

# Language switcher routes
lang_lt:
    path: /language/lt
    defaults: {_controller: ABBundle:Language:lithuanian }

lang_en:
    path: /language/en
    defaults: {_controller: ABBundle:Language:english }

# Pages routes
home:
    path: /{_locale}
    defaults: {_controller: ABBundle:Default:index }
    requirements:
        _locale: lt|en

about_oxbridge:
    path: /{_locale}/about/oxbridge
    # path: /about/oxbridge
    defaults: {_controller: ABBundle:Default:aboutOxbridge }
    requirements:
        _locale: lt|en

about_uk:
    path: /{_locale}/about/uk
    # path: /about/uk
    defaults: {_controller: ABBundle:Default:aboutUk }
    requirements:
        _locale: lt|en

support:
    path: /{_locale}/support
    # path: /support
    defaults: {_controller: ABBundle:Default:support }
    requirements:
        _locale: lt|en

# Aliases for support page as requested
support_parama:
    path: /parama
    defaults: {_controller: FrameworkBundle:Redirect:redirect, route: support, permanent: true }

support_ataskaita:
    path: /ataskaita
    defaults: {_controller: FrameworkBundle:Redirect:redirect, route: support, permanent: true }


mentor_list:
    path: /view/mentors/{category}/{page}
    defaults: {_controller: ABBundle:Default:mentorList, page: 1, category: 0 }
    options:
        expose: true

pupil_list:
    path: /view/pupils/{category}/{page}
    defaults: {_controller: ABBundle:Default:pupilList, page: 1, category: 0 }
    options:
        expose: true

settings:
    path: /settings/{id}
    defaults: { _controller: ABBundle:Profile:settings, id: null }

delete:
    path: /delete/{id}
    defaults: { _controller: ABBundle:Profile:delete }

message:
    path: /message/{mentorId}
    defaults: {_controller: ABBundle:Messaging:sendMessage}

user_export:
    path: /export
    defaults: {_controller: ABBundle:Default:userExport }

user_data:
    path: /export_data
    defaults: {_controller: ABBundle:Default:userData }
    options:
        expose: true
