parameters:
    ab_bundle.db.table_prefix: ab2_

services:
    ab_bundle.tblprefix_subscriber:
        class: AB\Bundle\Subscriber\TablePrefixSubscriber
        arguments: [%ab_bundle.db.table_prefix%]
        tags:
            - { name: doctrine.event_subscriber }
    ab_bundle.locale_listener:
        class: AB\Bundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }