parameters:
    ab_bundle.db.table_prefix: ab2_

services:
    ab_bundle.tblprefix_subscriber:
        class: AB\Bundle\Subscriber\TablePrefixSubscriber
        arguments: [%ab_bundle.db.table_prefix%]
        tags:
            - { name: doctrine.event_subscriber }